version: "3.4"
services:
  ecommerce-nodejs:
    image: node:19-alpine
    container_name: ecommerce-nodejs
    entrypoint: /bin/sh
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
